In [6]:
import pandas as pd
import numpy as np

#Task-1
#Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)
d1 = np.random.rand(4)
d2 = np.random.rand(4)
d3 = np.random.rand(4)
d4 = np.random.rand(4)

df = pd.DataFrame([d1,d2,d3,d4])
df

          0         1         2         3
0  0.985361  0.473715  0.382029  0.852940
1  0.867601  0.142891  0.335709  0.866522
2  0.376657  0.792799  0.527217  0.965320
3  0.227517  0.734800  0.138885  0.705313

In [7]:
#Task-2
#Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
df

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.985361        0.473715        0.382029        0.852940
1        0.867601        0.142891        0.335709        0.866522
2        0.376657        0.792799        0.527217        0.965320
3        0.227517        0.734800        0.138885        0.705313

In [9]:
#Task-3
#Find the descriptive statistics of the 'df' dataframe.

df.describe(include = "all")

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.614284        0.536051        0.345960        0.847524
std          0.368747        0.296581        0.160354        0.107223
min          0.227517        0.142891        0.138885        0.705313
25%          0.339372        0.391009        0.286503        0.816033
50%          0.622129        0.604258        0.358869        0.859731
75%          0.897041        0.749300        0.418326        0.891222
max          0.985361        0.792799        0.527217        0.965320

In [14]:
#Task-4
#Check for the null values in 'df' and find the data type of the columns
print('Finding Null Values\n')
print(df.isnull())
print('\nData Types \n')
print(df.dtypes)

Finding Null Values

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

Data Types

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

In [16]:
#Task-5
#Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

print('Displaying using location method.\n')
print(df.loc[0:,'Random value 2':'Random value 3'])
print('\nDisplaying using index location method.\n')
print(df.iloc[0:,1:3])

Displaying using location method.

   Random value 2  Random value 3
0        0.473715        0.382029
1        0.142891        0.335709
2        0.792799        0.527217
3        0.734800        0.138885

Displaying using index location method.

   Random value 2  Random value 3
0        0.473715        0.382029
1        0.142891        0.335709
2        0.792799        0.527217
3        0.734800        0.138885